# Copyright (c) 2020 Leeman Geophysical LLC.
# Distributed under the terms of the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

name: pylook
channels:
  - conda-forge/label/testing
  - conda-forge
dependencies:
  - python=3
  - numpy
  - pooch
  - matplotlib
  - jupyter
  - pytest>=2.4
  - pytest-cov
  - pytest-flake8
  - pytest-mpl
  - flake8-builtins!=1.4.0
  - flake8-comprehensions=1.4.1
  - flake8-copyright
  - flake8-docstrings
  - flake8-import-order
  - flake8-mutable
  - flake8-pep3101
  - flake8-print
  - flake8-quotes
  - flake8-rst-docstrings
  - pep8-naming
  - jupyterlab
  - pint
  - bokeh
  - setuptools_scm
